In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [12]:
arr
arr.ndim
arr.shape
arr.size

4

In [4]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
arr1
arr1.ndim
arr1.shape
arr1.size

8

In [6]:
arr2=np.array([[1,2],[3,4],[5,6]])

In [18]:
arr2
arr2.ndim
arr2.shape
arr2.size

6

In [8]:
arr3=np.array([[[1,2],[3,4],[5,6]]])

In [21]:
arr3
arr3.ndim
arr3.shape
arr3.size

6

In [24]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.full([2,3],3)

array([[3, 3, 3],
       [3, 3, 3]])

In [31]:
np.ones([2,2,6])

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])